"""Build the self-contained furnace Excel experiment notebook."""

from pathlib import Path
import pprint

import nbformat as nbf


PROJECT = Path(__file__).resolve().parents[2]
DESTINATION = PROJECT / "advanced_furnace_ml/notebooks/furnace_complete_excel_test.ipynb"
SOURCE_DIR = PROJECT / "advanced_furnace_ml/src/advanced_furnace_ml"


def markdown(title: str, body: str = ""):
    return nbf.v4.new_markdown_cell(f"## {title}\n\n{body}".strip())


def runtime_sources() -> dict[str, str]:
    """Snapshot the package into the notebook; runtime never reads SOURCE_DIR."""
    return {
        path.name: path.read_text(encoding="utf-8")
        for path in sorted(SOURCE_DIR.glob("*.py"))
        if path.name != "pipeline.py"
    }


def embedded_runtime_cell() -> str:
    rendered = pprint.pformat(runtime_sources(), width=120, sort_dicts=True)
    return (
        "# 运行时代码已作为字符串快照嵌入本 notebook；执行时不读取项目源码。\n"
        f"RUNTIME_SOURCES = {rendered}\n\n"
        "import importlib\n"
        "import sys\n"
        "RUNTIME_ROOT = OUTPUT_ROOT / 'runtime'\n"
        "PACKAGE_DIR = RUNTIME_ROOT / 'furnace_complete_runtime'\n"
        "PACKAGE_DIR.mkdir(parents=True, exist_ok=True)\n"
        "for filename, source_text in RUNTIME_SOURCES.items():\n"
        "    (PACKAGE_DIR / filename).write_text(source_text, encoding='utf-8')\n"
        "if str(RUNTIME_ROOT) not in sys.path:\n"
        "    sys.path.insert(0, str(RUNTIME_ROOT))\n"
        "importlib.invalidate_caches()\n"
        "print(f'已从 notebook 内嵌快照生成独立运行时: {PACKAGE_DIR}')"
    )


def build_notebook(destination: Path = DESTINATION) -> Path:
    notebook = nbf.v4.new_notebook()
    notebook["metadata"]["kernelspec"] = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }
    notebook["metadata"]["language_info"] = {"name": "python", "version": "3.11"}
    notebook["cells"] = [
        nbf.v4.new_markdown_cell(
            "# 完全自包含：Excel 全量训练与安全推荐测试\n\n"
            "本 notebook 每次只从 Excel 重新训练，不读取已有模型、报告、源码或其他 notebook。"
        ),
        markdown("配置与依赖检查"),
        nbf.v4.new_code_cell(
            "from pathlib import Path\n"
            "import importlib.util\n"
            "required = ['numpy', 'pandas', 'scipy', 'sklearn', 'joblib', 'openpyxl', 'lightgbm', 'catboost']\n"
            "missing = [name for name in required if importlib.util.find_spec(name) is None]\n"
            "if missing:\n"
            "    raise ImportError(f'缺少运行依赖: {missing}')\n"
            "EXCEL_NAME = '4_month_data_2026_02_01_2026_06_25.xlsx'\n"
            "search_roots = [Path.cwd(), *Path.cwd().parents]\n"
            "EXCEL_PATH = next((root / EXCEL_NAME for root in search_roots if (root / EXCEL_NAME).exists()), None)\n"
            "if EXCEL_PATH is None:\n"
            "    raise FileNotFoundError(f'未找到 Excel，请把 {EXCEL_NAME} 放在 notebook 工作目录或其父目录。')\n"
            "PROJECT_ROOT = EXCEL_PATH.parent\n"
            "OUTPUT_ROOT = PROJECT_ROOT / 'advanced_furnace_ml/complete_notebook_output'\n"
            "ARTIFACTS_DIR = OUTPUT_ROOT / 'artifacts'\n"
            "REPORTS_DIR = OUTPUT_ROOT / 'reports'\n"
            "for directory in (OUTPUT_ROOT, ARTIFACTS_DIR, REPORTS_DIR):\n"
            "    directory.mkdir(parents=True, exist_ok=True)\n"
            "print({'excel': str(EXCEL_PATH), 'isolated_output': str(OUTPUT_ROOT), 'missing_dependencies': missing})"
        ),
        nbf.v4.new_code_cell(embedded_runtime_cell()),
        markdown("Excel 数据质量检查"),
        nbf.v4.new_code_cell(
            "from furnace_complete_runtime.data import (\n"
            "    FEATURE_COLS, TARGET_COL, chronological_dev_lock_split, load_batch_data, mark_target_outliers,\n"
            ")\n"
            "from furnace_complete_runtime.validation import large_window_splits\n"
            "df = mark_target_outliers(load_batch_data(EXCEL_PATH))\n"
            "dev, locked = chronological_dev_lock_split(df, lock_size=44)\n"
            "splits = large_window_splits(len(dev))\n"
            "assert len(df) == 292\n"
            "assert len(dev) == 248\n"
            "assert len(locked) == 44\n"
            "expected_windows = [(0, 148, 148, 181), (0, 181, 181, 214), (0, 214, 214, 248)]\n"
            "observed_windows = [(int(tr.min()), int(tr.max()) + 1, int(va.min()), int(va.max()) + 1) for tr, va in splits]\n"
            "assert observed_windows == expected_windows\n"
            "display(df.head())\n"
            "display({'总炉次': len(df), '开发炉次': len(dev), '锁定炉次': len(locked), "
            "'高气耗异常标记数（保留）': int(df['is_high_gas_outlier'].sum())})"
        ),
        markdown("三个时间折与锁定集"),
        nbf.v4.new_code_cell(
            "import pandas as pd\n"
            "fold_design = pd.DataFrame([\n"
            "    {'fold': i + 1, 'train_start': w[0], 'train_end_exclusive': w[1], "
            "'valid_start': w[2], 'valid_end_exclusive': w[3], 'train_size': w[1]-w[0], 'valid_size': w[3]-w[2]}\n"
            "    for i, w in enumerate(observed_windows)\n"
            "])\n"
            "display(fold_design)\n"
            "print('已验证：每个验证窗口都严格晚于训练窗口，没有未来数据泄漏。')"
        ),
        markdown("完整模型矩阵与开发阶段选模"),
        nbf.v4.new_code_cell(
            "from furnace_complete_runtime.experiment import random_cv_reference, run_model_matrix\n"
            "print('开始从 Excel 训练完整模型矩阵；锁定44炉此时不参与选模。')\n"
            "experiment = run_model_matrix(dev, splits)\n"
            "selected_before_lock = experiment.selected_name\n"
            "model_cv_summary = experiment.summary.copy()\n"
            "model_cv_summary['selected_before_lock'] = model_cv_summary['candidate'].eq(selected_before_lock)\n"
            "chronological_fold_metrics = pd.concat(\n"
            "    [result.fold_metrics for result in experiment.results.values()], ignore_index=True\n"
            ")\n"
            "tree_tuning_summary = experiment.tree_tuning_summary.copy()\n"
            "random_cv_reference_table = random_cv_reference(experiment, n_splits=3, seed=42)\n"
            "required_candidates = {'OOFEnsemble', 'Ridge+LGBMResidual__direct', "
            "'Huber+LGBMResidual__direct', 'GPR__direct', 'LightGBM__direct'}\n"
            "assert required_candidates.issubset(set(model_cv_summary['candidate']))\n"
            "assert model_cv_summary['candidate'].nunique() == 19\n"
            "assert model_cv_summary.loc[model_cv_summary['selected_before_lock'], 'candidate'].item() == selected_before_lock\n"
            "experiment.freeze()\n"
            "display(model_cv_summary.round(4))\n"
            "display(tree_tuning_summary.round(4))\n"
            "display(random_cv_reference_table.head(12).round(4))\n"
            "print(f'开发阶段 Champion: {selected_before_lock}')\n"
            "print('包含 conformal_radius_90、时间折波动；GPR 行另含 native_model_std_mean。')"
        ),
        markdown("最后44炉锁定审计"),
        nbf.v4.new_markdown_cell(
            "开发阶段 Champion 已经在不查看最后44炉结果的情况下冻结。下面只做一次审计。"
            "锁定集不能反向参与选模；否则它就不再是独立测试集。"
        ),
        nbf.v4.new_code_cell(
            "from furnace_complete_runtime.experiment import audit_frozen_models\n"
            "locked_audit = audit_frozen_models(experiment, locked)\n"
            "assert len(locked_audit) == len(model_cv_summary) == 19\n"
            "assert int(len(locked)) == 44\n"
            "locked_rmse_winner = str(locked_audit.sort_values('rmse').iloc[0]['candidate'])\n"
            "interpretation = pd.DataFrame([\n"
            "    {'角色': '开发阶段 Champion', '模型': selected_before_lock, '用途': '按三个时间折预先选出的预测模型'},\n"
            "    {'角色': '锁定集 RMSE 优胜者', '模型': locked_rmse_winner, '用途': '最后44炉上的审计优胜者，不反向改写选模'},\n"
            "])\n"
            "required_audit_columns = {\n"
            "    'mae', 'rmse', 'wape', 'r2', 'error_gt_10pct_rate',\n"
            "    'rmse_bootstrap_low95', 'rmse_bootstrap_high95', 'interval_coverage_90',\n"
            "}\n"
            "assert required_audit_columns.issubset(locked_audit.columns)\n"
            "display(locked_audit.sort_values('rmse').round(4))\n"
            "display(interpretation)\n"
            "print(f'开发阶段 Champion: {selected_before_lock}')\n"
            "print(f'锁定集 RMSE 优胜者: {locked_rmse_winner}')\n"
            "print('锁定集不能反向参与选模。')"
        ),
        markdown("86000 kg 历史基准推导"),
        nbf.v4.new_code_cell(
            "import math\n"
            "import warnings\n"
            "import numpy as np\n"
            "from sklearn.base import clone\n"
            "from sklearn.exceptions import ConvergenceWarning\n"
            "from furnace_complete_runtime.data import (\n"
            "    DOOR_COUNT_COL, MELTING_COL, WEIGHT_COL,\n"
            ")\n"
            "from furnace_complete_runtime.recommendation import (\n"
            "    CONTROLLABLE_COLS, build_recommendation_context, fit_feasibility_reference,\n"
            "    historical_fallback, recommend_or_fallback, safety_gate,\n"
            ")\n"
            "TARGET_WEIGHT = 86000.0\n"
            "recommendation_context = build_recommendation_context(df, TARGET_WEIGHT, trust_ratio=0.10)\n"
            "similar_history_rows = len(recommendation_context.reference_df)\n"
            "low_gas_20pct_rows = max(1, math.ceil(similar_history_rows * 0.20))\n"
            "actual_baseline_gas = recommendation_context.actual_baseline_gas\n"
            "baseline_table = pd.DataFrame([\n"
            "    {'项目': '相似历史炉次数', '数值': similar_history_rows},\n"
            "    {'项目': '重量容差', '数值': recommendation_context.weight_tolerance},\n"
            "    {'项目': '低气耗20%炉次数', '数值': low_gas_20pct_rows},\n"
            "    {'项目': '相似历史实际气耗中位数', '数值': actual_baseline_gas},\n"
            "    {'项目': '低气耗20%实际气耗中位数', '数值': recommendation_context.historical_low_gas_median},\n"
            "])\n"
            "control_baseline_table = pd.DataFrame([\n"
            "    {'参数': column, '历史低气耗中位数': value}\n"
            "    for column, value in recommendation_context.baseline_controls.items()\n"
            "])\n"
            "assert similar_history_rows == 97\n"
            "assert low_gas_20pct_rows == 20\n"
            "assert abs(actual_baseline_gas - 3701.28) < 1e-9\n"
            "display(baseline_table)\n"
            "display(control_baseline_table.round(4))\n"
            "print('历史低气耗参数分别取中位数，不保证来自同一炉；后续用kNN检查联合组合。')\n"
            "feasibility_reference = fit_feasibility_reference(df)\n"
            "recommendation_candidate_names = [\n"
            "    'LightGBM__direct', 'GPR__direct', 'Ridge+LGBMResidual__direct',\n"
            "    'Huber+LGBMResidual__direct', 'OOFEnsemble',\n"
            "]\n"
            "full_recommendation_models = {}\n"
            "for candidate_name in recommendation_candidate_names:\n"
            "    model = clone(experiment.results[candidate_name].estimator_template)\n"
            "    with warnings.catch_warnings():\n"
            "        warnings.simplefilter('ignore', ConvergenceWarning)\n"
            "        model.fit(df[FEATURE_COLS], df[TARGET_COL])\n"
            "    full_recommendation_models[candidate_name] = model\n"
            "print('已在锁定审计完成后，用全部292炉拟合最终推荐候选模型。')"
        ),
        markdown("宽范围搜索诊断"),
        nbf.v4.new_markdown_cell(
            "该部分使用 historical 5%-95% 宽范围，只用于解释为什么优化器可能寻找边界或高不确定性参数，"
            "不把结果直接作为生产推荐。"
        ),
        nbf.v4.new_code_cell(
            "from dataclasses import replace\n"
            "from furnace_complete_runtime.optimization import genetic_search\n"
            "broad_bounds = {}\n"
            "for column in CONTROLLABLE_COLS:\n"
            "    low = float(recommendation_context.reference_df[column].quantile(0.05))\n"
            "    high = float(recommendation_context.reference_df[column].quantile(0.95))\n"
            "    if column == DOOR_COUNT_COL:\n"
            "        low, high = float(math.ceil(low)), float(math.floor(high))\n"
            "    broad_bounds[column] = (low, high)\n"
            "broad_context = replace(recommendation_context, bounds=broad_bounds, trust_ratio=1.0)\n"
            "broad_scored = genetic_search(\n"
            "    full_recommendation_models['LightGBM__direct'],\n"
            "    experiment.results['LightGBM__direct'].fold_models,\n"
            "    broad_context, feasibility_reference, budget=600, seed=42,\n"
            ")\n"
            "broad_best = broad_scored.sort_values('penalized_objective').iloc[0]\n"
            "broad_search_diagnostics = pd.DataFrame([{\n"
            "    'candidate': 'LightGBM__direct',\n"
            "    'search_range': 'historical 5%-95%',\n"
            "    'conservative_predicted_gas': float(broad_best['conservative_predicted_gas']),\n"
            "    'prediction_std': float(broad_best['prediction_std']),\n"
            "    'normalized_knn_distance': float(broad_best['normalized_knn_distance']),\n"
            "    'boundary_hit': bool(broad_best['boundary_hit']),\n"
            "    'boundary_pass': not bool(broad_best['boundary_hit']),\n"
            "    'uncertainty_pass_old_rule': bool(broad_best['prediction_std'] <= 0.50 * recommendation_context.target_iqr),\n"
            "    **{column: float(broad_best[column]) for column in CONTROLLABLE_COLS},\n"
            "}])\n"
            "display(broad_search_diagnostics.round(4))\n"
            "print('宽范围结果是风险诊断；低预测值若命中边界或折间分歧大，不进入生产候选。')"
        ),
        markdown("生产候选推荐与安全门"),
        nbf.v4.new_code_cell(
            "from furnace_complete_runtime.optimization import (\n"
            "    bayesian_search, compare_optimizers, genetic_search, random_search,\n"
            ")\n"
            "SEARCH_BUDGET = 600\n"
            "DEPLOYMENT_SEED = 42\n"
            "OPTIMIZER_FUNCTIONS = {\n"
            "    'random_search': random_search,\n"
            "    'genetic_algorithm': genetic_search,\n"
            "    'bayesian_optimization': bayesian_search,\n"
            "}\n"
            "optimizer_parts = []\n"
            "recommendation_rows = []\n"
            "recommendation_payloads = {}\n"
            "deployment_scored = {}\n"
            "for candidate_name in recommendation_candidate_names:\n"
            "    fold_models = experiment.results[candidate_name].fold_models\n"
            "    comparison = compare_optimizers(\n"
            "        full_recommendation_models[candidate_name], fold_models,\n"
            "        recommendation_context, feasibility_reference,\n"
            "        common_budget=SEARCH_BUDGET, seeds=(0, 1, 2), keep_results=False,\n"
            "    )\n"
            "    runs = comparison['runs'].copy()\n"
            "    runs['candidate'] = candidate_name\n"
            "    optimizer_parts.append(runs)\n"
            "    selected_optimizer = comparison['selected_optimizer']\n"
            "    scored = OPTIMIZER_FUNCTIONS[selected_optimizer](\n"
            "        full_recommendation_models[candidate_name], fold_models,\n"
            "        recommendation_context, feasibility_reference,\n"
            "        budget=SEARCH_BUDGET, seed=DEPLOYMENT_SEED,\n"
            "    )\n"
            "    deployment_scored[candidate_name] = scored\n"
            "    payload = recommend_or_fallback(scored, recommendation_context)\n"
            "    payload['candidate'] = candidate_name\n"
            "    payload['optimizer'] = selected_optimizer\n"
            "    recommendation_payloads[candidate_name] = payload\n"
            "    ordered = scored.sort_values('penalized_objective')\n"
            "    safe_row = next((row for _, row in ordered.iterrows() if safety_gate(row, recommendation_context).passes), None)\n"
            "    if safe_row is None:\n"
            "        fallback = historical_fallback(recommendation_context)\n"
            "        recommendation_rows.append({\n"
            "            'candidate': candidate_name, 'optimizer': selected_optimizer, 'source': fallback['source'],\n"
            "            'savings_pass': False, 'consensus_pass': False, 'feasibility_pass': False,\n"
            "            'boundary_pass': False, 'trust_region_pass': False, 'safety_pass': False,\n"
            "            'safety_reasons': '没有候选同时通过全部安全门',\n"
            "            **fallback['recommendation'],\n"
            "        })\n"
            "        continue\n"
            "    savings_pass = bool(safe_row['conservative_predicted_gas'] < actual_baseline_gas)\n"
            "    consensus_pass = bool(safe_row['fold_consensus_rate'] >= 2 / 3)\n"
            "    feasibility_pass = bool(safe_row['historically_feasible'])\n"
            "    boundary_pass = not bool(safe_row['boundary_hit'])\n"
            "    trust_region_pass = bool(safe_row['within_trust_region'])\n"
            "    safety_pass = all([savings_pass, consensus_pass, feasibility_pass, boundary_pass, trust_region_pass])\n"
            "    recommendation_rows.append({\n"
            "        'candidate': candidate_name, 'optimizer': selected_optimizer, 'source': 'model_optimization',\n"
            "        'actual_baseline_gas': actual_baseline_gas,\n"
            "        'conservative_predicted_gas': float(safe_row['conservative_predicted_gas']),\n"
            "        'estimated_saving_vs_actual_baseline': float(safe_row['estimated_saving_vs_actual_baseline']),\n"
            "        'fold_consensus_rate': float(safe_row['fold_consensus_rate']),\n"
            "        'prediction_std': float(safe_row['prediction_std']),\n"
            "        'normalized_knn_distance': float(safe_row['normalized_knn_distance']),\n"
            "        'savings_pass': savings_pass, 'consensus_pass': consensus_pass,\n"
            "        'feasibility_pass': feasibility_pass, 'boundary_pass': boundary_pass,\n"
            "        'trust_region_pass': trust_region_pass, 'safety_pass': safety_pass,\n"
            "        'safety_reasons': '',\n"
            "        **{column: float(safe_row[column]) for column in CONTROLLABLE_COLS},\n"
            "    })\n"
            "optimizer_comparison = pd.concat(optimizer_parts, ignore_index=True)\n"
            "recommendation_summary = pd.DataFrame(recommendation_rows)\n"
            "assert set(optimizer_comparison['evaluations']) == {SEARCH_BUDGET}\n"
            "assert set(optimizer_comparison['seed']) == {0, 1, 2}\n"
            "assert (recommendation_summary[DOOR_COUNT_COL].dropna() % 1 == 0).all()\n"
            "passing = recommendation_summary[recommendation_summary['safety_pass']]\n"
            "if passing.empty:\n"
            "    production_recommendation = historical_fallback(recommendation_context)\n"
            "    production_recommendation['candidate'] = selected_before_lock\n"
            "    production_recommendation['optimizer'] = 'historical_fallback'\n"
            "    production_recommendation_model = selected_before_lock\n"
            "else:\n"
            "    production_recommendation_model = str(\n"
            "        passing.sort_values('estimated_saving_vs_actual_baseline', ascending=False).iloc[0]['candidate']\n"
            "    )\n"
            "    production_recommendation = recommendation_payloads[production_recommendation_model]\n"
            "display(optimizer_comparison.round(4))\n"
            "display(recommendation_summary.round(4))\n"
            "display(pd.DataFrame([production_recommendation]).round(4))\n"
            "print('安全门要求：节气、至少2/3时间折共识、历史可行、不命中边界、位于±10%信任区域。')\n"
            "print('离线预计节省不等于工厂实际节省，必须经过现场受控试验。')"
        ),
        markdown("joblib 保存与重载复现"),
        nbf.v4.new_code_cell(
            "import json\n"
            "from datetime import datetime, timezone\n"
            "from furnace_complete_runtime.artifacts import save_bundle\n"
            "selected_result = experiment.results[selected_before_lock]\n"
            "prediction_model = clone(selected_result.estimator_template)\n"
            "with warnings.catch_warnings():\n"
            "    warnings.simplefilter('ignore', ConvergenceWarning)\n"
            "    prediction_model.fit(df[FEATURE_COLS], df[TARGET_COL])\n"
            "bundle = {\n"
            "    'artifact_version': 'advanced-furnace-1.0',\n"
            "    'notebook_artifact_version': 'furnace-complete-notebook-1.0',\n"
            "    'created_at': datetime.now(timezone.utc).isoformat(),\n"
            "    'feature_cols': list(FEATURE_COLS),\n"
            "    'training_batches': len(df), 'dev_batches': len(dev), 'locked_batches': len(locked),\n"
            "    'selected_model_name': selected_before_lock,\n"
            "    'locked_rmse_winner': locked_rmse_winner,\n"
            "    'prediction_model': prediction_model,\n"
            "    'prediction_fold_models': selected_result.fold_models,\n"
            "    'conformal_radius_90': selected_result.conformal_radius_90,\n"
            "    'model_cv_summary': model_cv_summary,\n"
            "    'tree_tuning_summary': tree_tuning_summary,\n"
            "    'random_cv_reference': random_cv_reference_table,\n"
            "    'locked_audit': locked_audit,\n"
            "    'training_data': df,\n"
            "    'recommendation_model_name': production_recommendation_model,\n"
            "    'recommendation_model': full_recommendation_models[production_recommendation_model],\n"
            "    'recommendation_fold_models': experiment.results[production_recommendation_model].fold_models,\n"
            "    'recommendation_optimizer': production_recommendation['optimizer'],\n"
            "    'recommendation_seed': DEPLOYMENT_SEED,\n"
            "    'recommendation_trust_ratio': 0.10,\n"
            "    'feasibility_reference': feasibility_reference,\n"
            "    'production_recommendation_86000': production_recommendation,\n"
            "    'offline_savings_disclaimer': '离线预计节省不等于工厂实际节省，必须经过现场受控试验。',\n"
            "}\n"
            "ARTIFACT_PATH = ARTIFACTS_DIR / 'furnace_complete_bundle.joblib'\n"
            "save_bundle(bundle, ARTIFACT_PATH)\n"
            "model_cv_summary.to_csv(REPORTS_DIR / 'model_cv_summary.csv', index=False)\n"
            "chronological_fold_metrics.to_csv(REPORTS_DIR / 'chronological_fold_metrics.csv', index=False)\n"
            "tree_tuning_summary.to_csv(REPORTS_DIR / 'tree_tuning_summary.csv', index=False)\n"
            "random_cv_reference_table.to_csv(REPORTS_DIR / 'random_cv_reference.csv', index=False)\n"
            "locked_audit.to_csv(REPORTS_DIR / 'locked_audit.csv', index=False)\n"
            "broad_search_diagnostics.to_csv(REPORTS_DIR / 'broad_search_diagnostics.csv', index=False)\n"
            "optimizer_comparison.to_csv(REPORTS_DIR / 'optimizer_comparison.csv', index=False)\n"
            "recommendation_summary.to_csv(REPORTS_DIR / 'recommendation_summary.csv', index=False)\n"
            "run_summary = {\n"
            "    'notebook_artifact_version': bundle['notebook_artifact_version'],\n"
            "    'training_batches': len(df), 'dev_batches': len(dev), 'locked_batches': len(locked),\n"
            "    'selected_before_lock': selected_before_lock,\n"
            "    'locked_rmse_winner': locked_rmse_winner,\n"
            "    'recommendation_model': production_recommendation_model,\n"
            "    'recommendation_optimizer': production_recommendation['optimizer'],\n"
            "    'recommendation_seed': DEPLOYMENT_SEED,\n"
            "    'production_recommendation_86000': production_recommendation,\n"
            "    'artifact_path': str(ARTIFACT_PATH),\n"
            "    'offline_savings_disclaimer': bundle['offline_savings_disclaimer'],\n"
            "}\n"
            "(REPORTS_DIR / 'run_summary.json').write_text(\n"
            "    json.dumps(run_summary, ensure_ascii=False, indent=2), encoding='utf-8'\n"
            ")\n"
            "print(f'已保存独立模型包: {ARTIFACT_PATH}')"
        ),
        nbf.v4.new_code_cell(
            "# 模拟新的推理进程：清除运行时模块，再从 notebook 生成的 runtime 目录重新导入。\n"
            "sample_X = df[FEATURE_COLS].iloc[[0]].copy()\n"
            "prediction_before = np.asarray(bundle['prediction_model'].predict(sample_X), dtype=float)\n"
            "for module_name in list(sys.modules):\n"
            "    if module_name == 'furnace_complete_runtime' or module_name.startswith('furnace_complete_runtime.'):\n"
            "        del sys.modules[module_name]\n"
            "importlib.invalidate_caches()\n"
            "reloaded_artifacts = importlib.import_module('furnace_complete_runtime.artifacts')\n"
            "reloaded_bundle = reloaded_artifacts.load_bundle(ARTIFACT_PATH)\n"
            "prediction_after = reloaded_artifacts.predict_bundle(reloaded_bundle, sample_X)['predicted_gas'].to_numpy()\n"
            "np.testing.assert_allclose(prediction_before, prediction_after, rtol=0, atol=1e-10)\n"
            "prediction_round_trip_atol_1e_10 = True\n"
            "replayed_recommendation = reloaded_artifacts.recommend_bundle(\n"
            "    reloaded_bundle, TARGET_WEIGHT, budget=SEARCH_BUDGET, seed=DEPLOYMENT_SEED\n"
            ")\n"
            "expected_recommendation = bundle['production_recommendation_86000']\n"
            "for column in CONTROLLABLE_COLS:\n"
            "    assert abs(replayed_recommendation['recommendation'][column] - expected_recommendation['recommendation'][column]) <= 1e-10\n"
            "assert abs(replayed_recommendation['conservative_predicted_gas'] - expected_recommendation['conservative_predicted_gas']) <= 1e-10\n"
            "recommendation_round_trip_atol_1e_10 = True\n"
            "def rejected(frame):\n"
            "    try:\n"
            "        reloaded_artifacts.predict_bundle(reloaded_bundle, frame)\n"
            "        return False\n"
            "    except ValueError:\n"
            "        return True\n"
            "malformed_missing_rejected = rejected(sample_X.drop(columns=FEATURE_COLS[0]))\n"
            "malformed_extra_rejected = rejected(sample_X.assign(额外字段=1))\n"
            "nonnumeric = sample_X.copy()\n"
            "nonnumeric.iloc[0, 0] = 'not-a-number'\n"
            "malformed_nonnumeric_rejected = rejected(nonnumeric)\n"
            "assert malformed_missing_rejected and malformed_extra_rejected and malformed_nonnumeric_rejected\n"
            "artifact_replay_tests = pd.DataFrame([\n"
            "    {'test': 'prediction_round_trip_atol_1e-10', 'passed': prediction_round_trip_atol_1e_10},\n"
            "    {'test': 'recommendation_round_trip_atol_1e-10', 'passed': recommendation_round_trip_atol_1e_10},\n"
            "    {'test': 'malformed_missing_rejected', 'passed': malformed_missing_rejected},\n"
            "    {'test': 'malformed_extra_rejected', 'passed': malformed_extra_rejected},\n"
            "    {'test': 'malformed_nonnumeric_rejected', 'passed': malformed_nonnumeric_rejected},\n"
            "])\n"
            "display(artifact_replay_tests)"
        ),
        markdown("最终自动测试汇总"),
        nbf.v4.new_code_cell(
            "final_test_summary = pd.DataFrame([\n"
            "    {'test': 'Excel炉次数=292', 'passed': len(df) == 292},\n"
            "    {'test': '开发/锁定=248/44', 'passed': len(dev) == 248 and len(locked) == 44},\n"
            "    {'test': '三个大时间折精确且无未来泄漏', 'passed': observed_windows == expected_windows},\n"
            "    {'test': '完整19候选模型矩阵', 'passed': model_cv_summary['candidate'].nunique() == 19},\n"
            "    {'test': '开发Champion在锁定审计前冻结', 'passed': experiment.frozen},\n"
            "    {'test': '锁定审计覆盖19模型和44炉', 'passed': len(locked_audit) == 19 and len(locked) == 44},\n"
            "    {'test': 'Conformal与GPR原生不确定性可用', 'passed': model_cv_summary['conformal_radius_90'].notna().all() and locked_audit['native_model_std_mean'].notna().sum() >= 2},\n"
            "    {'test': '三优化器统一600预算', 'passed': set(optimizer_comparison['evaluations']) == {600}},\n"
            "    {'test': '炉门次数保持整数', 'passed': bool((recommendation_summary[DOOR_COUNT_COL].dropna() % 1 == 0).all())},\n"
            "    {'test': '安全门分项完整', 'passed': {'savings_pass','consensus_pass','feasibility_pass','boundary_pass','trust_region_pass','safety_pass'}.issubset(recommendation_summary.columns)},\n"
            "    {'test': 'joblib预测和推荐可复现', 'passed': bool(artifact_replay_tests['passed'].all())},\n"
            "    {'test': '离线节省免责声明存在', 'passed': '不等于工厂实际节省' in bundle['offline_savings_disclaimer']},\n"
            "])\n"
            "assert bool(final_test_summary['passed'].all()), final_test_summary[~final_test_summary['passed']]\n"
            "display(final_test_summary)\n"
            "print(f'开发阶段 Champion: {selected_before_lock}')\n"
            "print(f'锁定集 RMSE 优胜者: {locked_rmse_winner}')\n"
            "print(f'生产推荐模型: {production_recommendation_model}')\n"
            "print(f\"安全门结果: {production_recommendation.get('safety_pass', False)}\")\n"
            "print(bundle['offline_savings_disclaimer'])"
        ),
    ]
    destination.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(notebook, destination)
    return destination


if __name__ == "__main__":
    print(build_notebook())
